/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cosre7.pms;

public class ServerApp {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new ServerApp().getGreeting());
    }
}
